services:
  app_crud:
    build: crud
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://crud:3306/crud?createDatabaseIfNotExist=true&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      DB_USER_NAME: root
      DB_PASSWORD: 1234
    restart: always
    depends_on:
      crud:
        condition: service_healthy
  crud:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234 
      MYSQL_PASSWORD: 
      MYSQL_DATABASE: crud
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost", "-p1234"]
      timeout: 10s
      retries: 3